db.restaurant.find({})
db.restaurant.find( {}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1} )
db.restaurant.find( {}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0 } )
db.restaurant.find( {}, {restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1, _id: 0} )
db.restaurant.find( { borough: "Bronx" } )
db.restaurant.find( { borough: "Bronx" }).limit(5)
db.restaurant.find( { borough: "Bronx" }).skip(5).limit(5)
db.restaurant.find( { "grades.score": { $gt: 90 } } )
db.restaurant.find( { grades: { $elemMatch: {score: { $gt: 80, $lt: 100 } } } })
db.restaurant.find( { "address.coord.0": { $lt: -95.754168 } } )
db.restaurant.find({ cuisine :{ $ne:'American'}, "grades.score" : {$gt : 70}, 'address.coord.0': {$lt: -65.754168}})
db.restaurant.find({ cuisine :{ $ne:'American'}, "grades.score" : {$gt : 70}, 'address.coord.0': {$lt: -65.754168}})
db.restaurant.find({ cuisine :{ $ne:"American"}, borough :{ $ne: "Brooklyn"}, "grades.grade": 'A'}).sort({cuisine: -1})
db.restaurant.find({ name: /^Wil/ } , {restaurant_id : 1, name : 1, borough : 1, cuisine : 1, _id:0} )
db.restaurant.find({ name: /ces$/ } , {restaurant_id : 1, name : 1, borough : 1, cuisine : 1, _id:0} )
db.restaurant.find({ name: /Reg/ } , {restaurant_id : 1, name : 1, borough : 1, cuisine : 1, _id:0} )
db.restaurant.find({ borough: "Bronx" , $or: [{ 'cuisine' : 'American'}, {'cuisine' : 'Chinese'}]})
db.restaurant.find({$or: [{borough: 'Staten Island'}, {borough: 'Queens'}, {borough: 'Bronx'}, {borough: 'Brooklyn'}]}, {restaurant_id : 1, name : 1, borough : 1, cuisine : 1, _id:0}) 
db.restaurant.find({ borough: { $nin: ['Staten Island', 'Queens', 'Bronx', 'Brooklyn']}}, {restaurant_id : 1, name : 1, borough : 1, cuisine : 1, _id:0})
db.restaurant.find({ "grades.score": { $lt: 11 } }, {restaurant_id : 1, name : 1, borough : 1, cuisine : 1, _id:0})
db.restaurant.find({$or : [{ cuisine : {$nin : ['American', 'Chinese', 'Bakery', 'Chicken']}}, {name:/^Wil/}]}, {_id:0, restaurant_id: 1, name:1, borough:1, cuisine:1 })
db.restaurant.find({ 'grades.grade': 'A', 'grades.score': 11, 'grades.date': ISODate('2014-08-11T00:00:00Z')}, {_id:0, restaurant_id: 1, name:1, grades:1})
db.restaurant.find({ 'grades.1.grade': 'A', 'grades.1.score': 9, 'grades.1.date': ISODate('2014-08-11T00:00:00Z')}, {_id:0, restaurant_id:1, name:1, grades:1})
db.restaurant.find({ 'address.coord.1' : {$gt: 42, $lt: 52}}, {_id:0, restaurant_id:1, name:1, address: 1})
db.restaurant.find({}).sort({name: 1})
db.restaurant.find({}).sort({name: -1})
db.restaurant.find({}).sort({cuisine: 1, borough: -1})
db.restaurant.find({'address.street': null})
db.restaurant.find({'address.coord': {$type : "double"}})
db.restuarant.find({'grades.score': {$mod : [7,0]}}, {restaurant_id : 1, name : 1, grades : 1, _id:0})
db.restaurant.find({name: /mon/}, {restaurant_id:1, name: 1, borough: 1, 'address.coord': 1, cuisine: 1, _id: 0})
db.restaurant.find({name:/^Mad/}, {restaurant_id:1, name: 1, borough: 1, 'address.coord': 1, cuisine: 1, _id: 0})
